########################################################################
##
##
##  experiments-tutorial.toml
##
##
##  This configuration file serves as input to the
##  `generate-tables.py` script, which parses log files from batch
##  runs of `run-all-in.sh` and generates a pdf witg tables and plots
##  of various metrics as defined below to analyse the results.
##
########################################################################





########################################################################
## base config options
########################################################################

[options]

# The `patterns` below in experiment definitions are relative to
# `base_path`.  `$config_dir` will be substituted by the folder where
# this config file resides in.
base_path = "$config_dir"

# The output path defines where generated plots and exported latex
# tables are placed.
output_path = "$config_dir/tables/experiments-tutorial"

# The loaded logs of experiments are cached in this folder for faster
# repeated table generation.
cache_dir = "$config_dir/tables/cache"

# If this is true, the generated pdf contains pages of different sizes
# to fit the results in each section. Otherwise, a regular PDF with A4
# pages in generated.
screenread = true

# Uncomment the following to force re-loading of logs and ignoring the
# cache. Alternatively, you can just delete the cache folder.
#overwrite_cache = true

# You can optionally import experiment definitions from another config
# file.
#import_experiments = ["$config_dir/experiments.toml"]


########################################################################
## experiment definition
########################################################################

# Here we define the different experiments for which we want to load
# logs. One experiment is a particular solver configuration run on a
# set of sequences (each sequence may appear at most once in the same
# experiment). The `name` is used to refer to the experiment later in
# this config file. The `display_name` is shown in generated table
# headers and plot labels. The `pattern` defines a "glob" pattern that
# matches all folders which should be searched for logs. This is
# relative to the `base_path` defined above.

[[experiments]]
name = "qr_float"
display_name = "$\\sqrt{BA}$-32"
pattern = "01_tutorial/*/1_*/*qr_float*"

[[experiments]]
name = "qr_double"
display_name = "$\\sqrt{BA}$-64"
pattern = "01_tutorial/*/1_*/*qr_double*"

[[experiments]]
name = "explicitsc_float"
display_name = "explicit-32"
pattern = "01_tutorial/*/1_*/*explicitsc_float*"

[[experiments]]
name = "explicitsc_double"
display_name = "explicit-64"
pattern = "01_tutorial/*/1_*/*explicitsc_double*"


########################################################################
## substitutions
########################################################################

# Substitutions allow to reuse the same config elements below in the
# results definitions to avoid duplicating the same information many
# times, for example the list of experiments we want to include or
# certain global parameters.
#
# There are two ways in which the substitutions can be referred
# to. For a substitution FOOBAR, you can use the string "<FOOBAR>" and
# the entire string will be replaced by the value of FOOBAR. In
# particular, the result is not neccessarily a string, but may be for
# example a list. Additionally, you can do in-string substitution such
# as "... some text ${FOOBAR} ..." and the value will be formatted
# into the string. This can be useful e.g. for figure titles.
#
# For convenience, you can define multiple [[substitutions]]
# tables. All entries will be merged.

[[substitutions]]
EXPERIMENTS = [
    "qr_float",
    "qr_double",
    "explicitsc_float",
    "explicitsc_double",
]
RELATIVE_TO_EXPERIMENT = "explicitsc_double"

[[substitutions]]
TOLERANCES = [1e-1, 1e-2, 1e-3]
YLIM_TOLERANCE_TOP = 1.75
YLIM_TOLERANCE_BOTTOM = -0.1


################################################################################
## results
################################################################################

# 'results' is a list of toml tables that define 'sections' (== pages
# in 'screenread' mode), latex tables or plots, i.e. what evaluations
# you want in the resulting pdf.
#
# Each item has a 'show' parameter that allows to quickly exclude it
# from the generated pdf. Excluding a section also excludes all
# contained tables and plots.


################################################################################
################################################################################
[[results]]
class = "section"
name = "tutorial plots"
pagewidth = "30cm"
show = true


######################################################################
# PERFORMANCE PROFILES show percentage of problems solved to a given
# accuracy vs relative runtime. The accuracy thresholds are determined
# as "fraction of cost reduced" in the interval of "initial cost" to
# "best final cost achieved by any solver". Relative runtime is the
# time needed to achieve the given accuracy threshold relative to the
# fastest solver on that sequence (i.e. the best solver for each
# sequence has relative runtime 1).  Performance profiles are a great
# way to show the runtime / accurcay tradeoff of different solvers
# across a range of different problems with different orders of
# magnitude in problem size.
######################################################################

[[results]]
show = true
class = "plot"
type = "performance_profile"
name = "all"
#filter_regex = "trafalgar|dubrovnik|venice|final"
reverse_zorder = true
experiments = "<EXPERIMENTS>"
tolerances = "<TOLERANCES>"
xlimits.right = [8,5,5]


######################################################################
# CONVERGENCE PLOTS show cost vs time (cost_time), cost vs iterations
# (cost_it), trust-region-radius vs iterations (tr_radius),
# inner-iterations vs iterations (inner_it) or memory vs iterations
# (memory).
######################################################################

[[results]]
show = true
class = "plot"
name = "convergence"
type = "bal_cost"
plot_tolerances = true
tolerances = "<TOLERANCES>"
bal_cost_include = ["cost_time"]
figsize = [3.2, 2.7]
ylabel = false
plot_cost_semilogy = true
ylim_tolerance.bottom = "<YLIM_TOLERANCE_BOTTOM>"
ylim_tolerance.top = "<YLIM_TOLERANCE_TOP>"
xlim_time.left = -0.04
xlim_time.right = 2.0
reverse_zorder = true
title = "ladybug138"
sequence = "ladybug138"
experiments = "<EXPERIMENTS>"


######################################################################
# MEMORY PLOTS show peak memory vs problem size
######################################################################

[[results]]
show = true
class = "plot"
type = "memory"
#legend_loc = false
problem_size_variants = ["obs"]
figsize = [5,3]
best_fit_line = false
reverse_zorder = true
name = "ladybug"
filter_regex = "ladybug"
experiments = "<EXPERIMENTS>"


################################################################################
################################################################################
[[results]]
class = "section"
name = "tutorial results tables"
pagewidth = "30cm"
show = true


######################################################################
# RESULTS TABLES show metric values for each run, i.e. one entry for
# each sequence and solver. You can show one or more metrics. Various
# options to compute metrics not as absolute values but realtive to a
# baseline solver or relative to another metric. Best and second best
# values are automatically indicated. The `decimals` property defines
# the number of decimals used for this (can be different from
# `display_decimals`).
######################################################################

[[results]]
class = "results_table"
name = "cost relative to ${RELATIVE_TO_EXPERIMENT}"
escape_latex_header = false
export_latex = "results_cost"
experiments = "<EXPERIMENTS>"
metrics = [
    {name = "cost", display_name = "final cost", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>", geometric_mean = true, decimals = 3, format_string="{:.3f}"},
]

[[results]]
class = "results_table"
name = "total runtime absolute and relative to ${RELATIVE_TO_EXPERIMENT}"
escape_latex_header = false
experiments = "<EXPERIMENTS>"
metrics = [
    {name = "solver_total_time"},
    {name = "solver_total_time", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>", geometric_mean = true, decimals = 3, format_string="{:.3f}", display_name="t total (relative)" },
]

[[results]]
class = "results_table"
name = "outer iterations"
escape_latex_header = false
experiments = "<EXPERIMENTS>"
metrics = [
    "num_it_total",
    "num_it_valid",
]

[[results]]
class = "results_table"
escape_latex_header = false
name = "total inner iterations"
experiments = "<EXPERIMENTS>"
metrics = [
    "num_it_inner",
]

[[results]]
class = "results_table"
escape_latex_header = false
name = "peak memory"
experiments = "<EXPERIMENTS>"
metrics = [
    "resident_memory_peak",
]

################################################################################
################################################################################
[[results]]
class = "section"
name = "tutorial summarize sequences table"
pagewidth = "30cm"
show = true


######################################################################
# SEQUENCE SUMMARY TABLES show metric averaged over all sequences,
# showing a single value for each solver. Often, averages over
# absolute metric values doesn't make much sense for problems of very
# different magnitude, so we often consider metric values relative to
# a different metric (e.g. linear solver time as a fraction of total
# solver time) or relaitve to one of the other solvers (e.g. showing
# speedup relative to a baseline). Different options to average like
# geometric or arithmetic mean are supported.
######################################################################

[[results]]
class = "summarize_sequences_table"
name = "(relative) metrics averaged over all tutorial sequences"
escape_latex_header = false
export_latex = "summarize_sequences"
experiments = "<EXPERIMENTS>"
metrics = [
    {name = "cost", display_name = "final cost (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "num_it_total", display_name = "#it (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "num_it_valid", display_name = "#it valid (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "num_it_successful", display_name = "#it succ (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "num_it_inner", display_name = "#inner-it (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "num_it_total"},
    {name = "num_it_successful"},
    {name = "num_it_inner"},
    {name = "solver_total_time", display_name = "t total (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "solver_linear_solver_time", display_name = "t lin-solve (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
    {name = "resident_memory_peak", display_name = "mem peak (relative)", relative_to_experiment = "<RELATIVE_TO_EXPERIMENT>"},
]


################################################################################
################################################################################
[[results]]
class = "section"
name = "tutorial problem info table"
pagewidth = "30cm"
show = true


######################################################################
# OVERVIEW TABLES show some static info about the problems (sequences)
# such as number of cameras, landmarks, observations etc. It is
# independent of the solver, as all properties are computed on the
# initialization.
######################################################################

[[results]]
class = "overview_table"
name = "Problem size"
export_latex = "problem_size"
columns = [
    { name = "<RELATIVE_TO_EXPERIMENT>", metrics = ["#cam", "#lm", "#obs", "#obs-per-cam", "#obs-per-lm-mean", "#obs-per-lm-stddev", "#obs-per-lm-max"] },
]


################################################################################
################################################################################
[[results]]
class = "section"
name = "tutorial convergence plots for all sequences"
show = true

[[substitutions]]
TUTORIAL_SEQUENCES = ["ladybug49", "ladybug73", "ladybug138", "ladybug318", "ladybug372", "ladybug412", "ladybug460", "ladybug539", "ladybug598", "ladybug646"]

######################################################################
# TEMPLATES define a list of arguments and allow advanced
# substitutions to generate multiple plots or tables at the same
# time.
######################################################################

[[templates]]
_name = "CONVERGENCE"
_arguments = ["SEQUENCE"]
class = "plot"
name = "convergence"
type = "bal_cost"
sequence = "<SEQUENCE>"
experiments = "<EXPERIMENTS>"
plot_tolerances = true
tolerances = "<TOLERANCES>"
#bal_cost_include = ["cost_time"]
plot_cost_semilogy = true
ylim_tolerance.bottom = -0.1
ylim_tolerance.top = 1.75
xlim_time_fastest.right = 1
xlim_time_fastest.left = -0.02
reverse_zorder = true
#figsize = [16.0, 2.7]  # <-- this is good with no "suptitle"
figsize = [16.0, 3.0]
suptitle = "${SEQUENCE}"


[[results]]
  [results._template]
  _name = "CONVERGENCE"
  SEQUENCE = {_argument = "product", _value = "<TUTORIAL_SEQUENCES>"}

