FROM ubuntu:22.04

# non-persistent environment variables
ARG DEBIAN_FRONTEND=noninteractive

# Basic packages
RUN apt-get update && apt-get install -y \
    apt-utils \
    apt-transport-https \
    software-properties-common \
    locales \
    wget \
    curl

# Set the locale
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# PPAs
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add - && \
    apt-add-repository -y "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-16 main"

# updates from clang repo
RUN apt-get update && apt-get dist-upgrade -y

# Install base C++ dev tools
RUN apt-get update && apt-get install -y \
    build-essential \
    clang-14 \
    clang-15 \
    clang-16 \
    g++-11 \
    g++-12 \
    libc++-15-dev \
    clang-format-15 \
    clang-tidy-15 \
    cmake \
    pkg-config \
    git-core \
    git-lfs \
    ccache

# cannot install libc++-dev due to imcompatibility with libgoogle-glog-dev
# https://bugs.launchpad.net/ubuntu/+source/google-glog/+bug/1991919
#    libc++-dev \

# Python
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    libpython3-all-dev
RUN pip3 install -U pip setuptools
RUN pip3 install -U cmake cmake_format
RUN pip3 install -U yapf
ENV PATH="/usr/local/bin:${PATH}"

# Install libraries
RUN apt-get update && apt-get install -y \
    libgoogle-glog-dev \
    libgflags-dev \
    libtbb-dev \
    libeigen3-dev \
    libatlas-base-dev \
    libsuitesparse-dev \
    libglew-dev \
    ffmpeg \
    libavcodec-dev \
    libavutil-dev \
    libavformat-dev \
    libswscale-dev \
    libavdevice-dev \
    libjpeg-dev \
    libpng-dev \
    libtiff5-dev \
    libopenexr-dev
